### ISSUE TITLE
Enable CocoaPods deploy from CircleCI

### ISSUE THREAD

**Issue by ZevEisenberg** [Raizlabs/BonMot#289]
I already added the requisite environment variable to Circle and added ci@raizlabs.com as a repo owner. Now just need to add this to circle.yml:

```yml
deployment:
    release:
        tag: /\d+(\.\d+)*(\..*)*/
    commands:
        - bundle exec pod trunk push
```

This lets Circle deploy to CocoaPods trunk whenever we push a tag that looks like a version number.

**Comment by ZevEisenberg** [comment]
Fixed in 4b637758ddc10f2d8fe174bf54e2099f89870b7b. This will take effect in all releases post-5.0.

**Comment by ZevEisenberg** [comment]
Warning: the code snipped above is both incorrectly indented and also has an older regex. Here's the good version, copied from [Anchorage](https://github.com/Raizlabs/Anchorage):

```yml
deployment:
  release:
    tag: /\d+(\.\d+)*(-.*)*/
    commands:
      - bundle exec pod trunk push
```
